version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-containya
    restart: always

    ports:
      - "80:80"
      - "443:443"

    environment:
      - TZ=Asia/Tokyo

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./html:/var/www/html:ro
      - nginx-html-wp:/var/www/html/wp:ro
      - nginx-certific8s:/etc/ssl/certs:ro
      - ./logs:/var/log/nginx

    networks:
      - containya-network

volumes:
  nginx-certific8s:
    external: true
  nginx-html-wp:
    external: true

networks:
  containya-network:
    external: true
