version: '2'
services:
  app:
    image: wordpress:6.2.2-php8.0-fpm-alpine
    container_name: wp-app-containya
    volumes:
      - nginx-html-wp:/var/www/html
#      - ./app/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./app/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - db
    networks:
      - default
      - containya-network

  db:
    image: mysql:8
    container_name: wp-db-containya
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - default

volumes:
  db-data:
  nginx-html-wp:
    external: true

networks:
  default:
  containya-network:
    external: true
